AppGestionScolarite/Controllers/ModulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AppGestionScolarite.Data;
using AppGestionScolarite.Models;

namespace AppGestionScolarite.Controllers
{
    public class ModulesController : Controller
    {
        private IWebHostEnvironment _webHostEnvironment;
        private readonly ApplicationDbContext _context;

        public ModulesController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Modules
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Modules.Include(module => module.UnitePedagogique)
                .Include(module => module.Parcours);
            var res = await applicationDbContext.ToListAsync();
            return View(res);
        }

        // GET: Modules/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Modules == null)
            {
                return NotFound();
            }

            var @module = await _context.Modules
                .Include(module => module.UnitePedagogique)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@module == null)
            {
                return NotFound();
            }

            return View(@module);
        }

        // GET: Modules/Create
        public IActionResult Create()
        {
            ViewData["UnitePedagogiqueId"] = new SelectList(_context.UnitePedagogique, "Id", "Designation");
            ViewData["ParcoursId"] = new SelectList(_context.Parcours, "Id", "Nom");
            return View();
        }

        // POST: Modules/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nom,Resume,Infos,Logo,ParcoursId,UnitePedagogiqueId")] Module @module, IFormFile? Logo)
        {
            if (ModelState.IsValid)
            {
                if (Logo != null)
                {
                    string rootPath = _webHostEnvironment.WebRootPath;
                    string fileName = Path.GetFileNameWithoutExtension(Logo.FileName) + "_" +
                               Guid.NewGuid() +
                               Path.GetExtension(Logo.FileName);
                    string path = Path.Combine(rootPath + "/photoLogoModule/", fileName);
                    
                    var fileStream = new FileStream(path, FileMode.Create);
                    await Logo.CopyToAsync(fileStream);
                    fileStream.Close();
                    @module.Logo = fileName;
                }
                var parcoursToAdd = await _context.Parcours.FindAsync(@module.ParcoursId);
                //if parcoursToAdd  null....
                var unitePedagogiqueToAdd = await _context.UnitePedagogique.FindAsync(@module.UnitePedagogiqueId);
                //if unitePedagogiqueToAdd  null....
                if (@module.Parcours == null)
                    @module.Parcours = new List<Parcour>();
                @module.Parcours.Add(parcoursToAdd);
                @module.UnitePedagogique = unitePedagogiqueToAdd;

                _context.Add(@module);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ParcoursId"] = new SelectList(_context.Parcours, "Id", "Id", @module.ParcoursId);
            ViewData["UnitePedagogiqueId"] = new SelectList(_context.UnitePedagogique, "Id", "Id", @module.UnitePedagogiqueId);
            return View(@module);
        }

        // GET: Modules/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Modules == null)
            {
                return NotFound();
            }

            var @module = await _context.Modules.FindAsync(id);
            if (@module == null)
            {
                return NotFound();
            }
            ViewData["ParcoursId"] = new SelectList(_context.Parcours, "Id", "Nom");
            ViewData["UnitePedagogiqueId"] = new SelectList(_context.Set<UnitePedagogique>(), "Id", "Designation", @module.UnitePedagogiqueId);
            return View(@module);
        }

        // POST: Modules/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nom,Resume,Infos,Logo,ParcoursId,UnitePedagogiqueId")] Module @module, IFormFile? Logo)
        {
            if (id != @module.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (Logo != null)
                    {
                        string rootPath = _webHostEnvironment.WebRootPath;
                        string fileName = Path.GetFileNameWithoutExtension(Logo.FileName) + "_" +
                                   Guid.NewGuid() +
                                   Path.GetExtension(Logo.FileName);
                        string path = Path.Combine(rootPath + "/photoLogoModule/", fileName);

                        var fileStream = new FileStream(path, FileMode.Create);
                        await Logo.CopyToAsync(fileStream);
                        fileStream.Close();
                        module.Logo = fileName;
                    }
                    _context.Update(@module);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ModuleExists(@module.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UnitePedagogiqueId"] = new SelectList(_context.Set<UnitePedagogique>(), "Id", "Id", @module.UnitePedagogiqueId);
            ViewData["ParcoursId"] = new SelectList(_context.Parcours, "Id", "Id", @module.ParcoursId);
            return View(@module);
        }

        // GET: Modules/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Modules == null)
            {
                return NotFound();
            }

            var @module = await _context.Modules
                .Include(module =>  module.UnitePedagogique)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@module == null)
            {
                return NotFound();
            }

            return View(@module);
        }

        // POST: Modules/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Modules == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Modules'  is null.");
            }
            var @module = await _context.Modules.FindAsync(id);
            if (@module != null)
            {
                _context.Modules.Remove(@module);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ModuleExists(int id)
        {
          return (_context.Modules?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

AppGestionScolarite/Controllers/ParcoursController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AppGestionScolarite.Data;
using AppGestionScolarite.Models;

namespace AppGestionScolarite.Controllers
{
    public class ParcoursController : Controller
    {
        private readonly ApplicationDbContext _context;

        private IWebHostEnvironment _webHostEnvironment;
        public ParcoursController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Parcours
        public async Task<IActionResult> Index()
        {
              return _context.Parcours != null ? 
                          View(await _context.Parcours.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Parcours'  is null.");
        }

        // GET: Parcours/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Parcours == null)
            {
                return NotFound();
            }

            var parcour = await _context.Parcours
                .FirstOrDefaultAsync(m => m.Id == id);
            if (parcour == null)
            {
                return NotFound();
            }

            return View(parcour);
        }

        // GET: Parcours/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Parcours/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nom,Resume,Infos,Logo")] Parcour parcour, IFormFile? Logo)
        {
            if (ModelState.IsValid)
            {
                if (Logo != null)
                {
                    string rootPath = _webHostEnvironment.WebRootPath;
                    string fileName = Path.GetFileNameWithoutExtension(Logo.FileName) + "_" +
                               Guid.NewGuid() +
                               Path.GetExtension(Logo.FileName);
                    string path = Path.Combine(rootPath + "/photoLogoParcour/", fileName);

                    var fileStream = new FileStream(path, FileMode.Create);
                    await Logo.CopyToAsync(fileStream);
                    fileStream.Close();
                    parcour.Logo = fileName;
                }

                _context.Add(parcour);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(parcour);
        }

        // GET: Parcours/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Parcours == null)
            {
                return NotFound();
            }

            var parcour = await _context.Parcours.FindAsync(id);
            if (parcour == null)
            {
                return NotFound();
            }
            return View(parcour);
        }

        // POST: Parcours/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nom,Resume,Infos,Logo")] Parcour parcour, IFormFile? Logo)
        {
            if (id != parcour.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (Logo != null)
                    {
                        string rootPath = _webHostEnvironment.WebRootPath;
                        string fileName = Path.GetFileNameWithoutExtension(Logo.FileName) + "_" +
                                   Guid.NewGuid() +
                                   Path.GetExtension(Logo.FileName);
                        string path = Path.Combine(rootPath + "/photoLogoParcour/", fileName);

                        var fileStream = new FileStream(path, FileMode.Create);
                        await Logo.CopyToAsync(fileStream);
                        fileStream.Close();
                        parcour.Logo = fileName;
                    }
                    _context.Update(parcour);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ParcourExists(parcour.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(parcour);
        }

        // GET: Parcours/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Parcours == null)
            {
                return NotFound();
            }

            var parcour = await _context.Parcours
                .FirstOrDefaultAsync(m => m.Id == id);
            if (parcour == null)
            {
                return NotFound();
            }

            return View(parcour);
        }

        // POST: Parcours/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Parcours == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Parcours'  is null.");
            }
            var parcour = await _context.Parcours.FindAsync(id);
            if (parcour != null)
            {
                _context.Parcours.Remove(parcour);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ParcourExists(int id)
        {
          return (_context.Parcours?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

AppGestionScolarite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TPServiceScolarite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TPServiceScolarite.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TPServiceScolarite</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@

                        <li class="nav-item">
                            <div class="collapse navbar-collapse " id="navbarNavDarkDropdown">
                                <ul class="navbar-nav  ">
                                    <li class="nav-item dropdown ">
                                        <a class="nav-link dropdown-toggle text-dark " href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            Parcours
                                        </a>
                                        <ul class="dropdown-menu bg-info bg-opacity-25 " aria-labelledby="navbarDarkDropdownMenuLink">
                                            <li><a class="dropdown-item text-reset" asp-area="" asp-controller="Parcours" asp-action="Index"> Liste des Parcours</a></li>
                                            <li><a class="dropdown-item text-reset" asp-area="" asp-controller="Parcours" asp-action="Create"> Creation d'un parcours</a></li>
                                            @*<li><a class="dropdown-item text-reset" asp-area="" asp-controller="Parcours" asp-action="Delete">Suppression d'un parcours </a></li>
                                            <li><a class="dropdown-item text-reset" asp-area="" asp-controller="Parcours" asp-action="Details">Détails d'un parcours</a> </li>
                                            <li><a class="dropdown-item text-reset" asp-area="" asp-controller="Parcours" asp-action="Edit"> Modifications d'un parcours</a> </li>*@
                                        </ul>

                                    </li>
                                </ul>
                            </div>
                        </li>

                        <li class="nav-item">
                            <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                                <ul class="navbar-nav">
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            Modules
                                        </a>
                                        <ul class="dropdown-menu bg-info bg-opacity-25 " aria-labelledby="navbarDarkDropdownMenuLink">
                                            <li><a class="dropdown-item text-reset" asp-area="" asp-controller="Modules" asp-action="Index"> Liste des Modules</a></li>
                                            <li><a class="dropdown-item text-reset" asp-area="" asp-controller="Modules" asp-action="Create"> Creation d'un nouveau Module</a></li>
                                            @*<li><a class="dropdown-item text-reset" asp-area="" asp-controller="Modules" asp-action="Delete">Suppression d'un Module </a></li>
                                            <li><a class="dropdown-item text-reset" asp-area="" asp-controller="Modules" asp-action="Details">Détails d'un Module</a> </li>
                                            <li><a class="dropdown-item text-reset" asp-area="" asp-controller="Modules" asp-action="Edit"> Modification d'un Module</a> </li>*@
                                        </ul>

                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li class="nav-item">
                            <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                                <ul class="navbar-nav">
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            Unité Pedagogique
                                        </a>
                                        <ul class="dropdown-menu bg-info bg-opacity-25 " aria-labelledby="navbarDarkDropdownMenuLink">
                                            <li><a class="dropdown-item text-reset" asp-area="" asp-controller="UnitePedagogiques" asp-action="Index"> Liste des Unités Pédagogique</a></li>
                                            <li><a class="dropdown-item text-reset" asp-area="" asp-controller="UnitePedagogiques" asp-action="Create"> Creation d'une nouvelle Unite </a></li>
                                            @*<li><a class="dropdown-item text-reset" asp-area="" asp-controller="Modules" asp-action="Delete">Suppression d'un Module </a></li>
                                            <li><a class="dropdown-item text-reset" asp-area="" asp-controller="Modules" asp-action="Details">Détails d'un Module</a> </li>
                                            <li><a class="dropdown-item text-reset" asp-area="" asp-controller="Modules" asp-action="Edit"> Modification d'un Module</a> </li>*@
                                        </ul>

                                    </li>
                                </ul>
                            </div>
                        </li>

                        <li class="nav-item">
                            <div class="collapse navbar-collapse " id="navbarNavDarkDropdown">
                                <ul class="navbar-nav  ">
                                    <li class="nav-item dropdown ">
                                        <a class="nav-link dropdown-toggle text-dark " href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            Session
                                        </a>
                                        <ul class="dropdown-menu bg-info bg-opacity-25 " aria-labelledby="navbarDarkDropdownMenuLink">
                                            <li><a class="dropdown-item text-reset" asp-area="" asp-controller="Sessions" asp-action="Index"> Liste des Sessions</a></li>
                                            <li><a class="dropdown-item text-reset" asp-area="" asp-controller="Sessions" asp-action="Create"> Creation d'un Session</a></li>
                                            @*<li><a class="dropdown-item text-reset" asp-area="" asp-controller="Parcours" asp-action="Delete">Suppression d'un parcours </a></li>
                                            <li><a class="dropdown-item text-reset" asp-area="" asp-controller="Parcours" asp-action="Details">Détails d'un parcours</a> </li>
                                            <li><a class="dropdown-item text-reset" asp-area="" asp-controller="Parcours" asp-action="Edit"> Modifications d'un parcours</a> </li>*@
                                        </ul>

                                    </li>
                                </ul>
                            </div>
                        </li>

                        <li class="nav-item">
                            <div class="collapse navbar-collapse " id="navbarNavDarkDropdown">
                                <ul class="navbar-nav  ">
                                    <li class="nav-item dropdown ">
                                        <a class="nav-link dropdown-toggle text-dark " href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            Cart items
                                        </a>
                                        <ul class="dropdown-menu bg-info bg-opacity-25 " aria-labelledby="navbarDarkDropdownMenuLink">
                                            <li><a class="dropdown-item text-reset" asp-area="" asp-controller="CartItems" asp-action="Index"> Liste des cart items</a></li>
                                            <li><a class="dropdown-item text-reset" asp-area="" asp-controller="CartItems" asp-action="Create"> Creation d'un cart items</a></li>
                                            @*<li><a class="dropdown-item text-reset" asp-area="" asp-controller="CartItems" asp-action="Delete">Suppression d'un cart items </a></li>
                                            <li><a class="dropdown-item text-reset" asp-area="" asp-controller="CartItems" asp-action="Details">Détails d'un cart items</a> </li>
                                            <li><a class="dropdown-item text-reset" asp-area="" asp-controller="CartItems" asp-action="Edit"> Modifications d'un cart items</a> </li>*@
                                        </ul>

                                    </li>
                                </ul>
                            </div>
                        </li>

                    </ul>
                    <ul>
                        <li>
                            <button class="btn btn-danger" >
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bag-heart" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M10.5 3.5a2.5 2.5 0 0 0-5 0V4h5v-.5Zm1 0V4H15v10a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4h3.5v-.5a3.5 3.5 0 1 1 7 0ZM14 14V5H2v9a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1ZM8 7.993c1.664-1.711 5.825 1.283 0 5.132-5.825-3.85-1.664-6.843 0-5.132Z" />
                                </svg>
                            </button>
                        </li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TPServiceScolarite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>